# Hugo site title
title: BookSmart Financials

# The URL to the root of the website
baseURL: https://booksmartfinancials.github.io

# Language code for the website
languageCode: en-us
languageName: English

# When enabled a robots.txt file will be created in the site root that allows search engines to crawl the entire site
enableRobotsTXT: true

# Kinds of content that should be excluded from the generated /sitemap.xml file
disableKinds:
  - taxonomy
  - term

menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: Services
      url: '#services'
      weight: 2
    - name: Contact
      url: '#contact'
      weight: 5

  sitemap:
    - name: Home
      url: '#'
      weight: 1
    - name: Contact
      url: 'contact'
      weight: 2

params:
  # Website author name (who this website belongs to)
  author: Tamara Jeremic

  # The company’s name. This will be displayed in article footers, and on the homepage when the profile layout is used.
  name: BookSmart Financials

  # The website description. This will be used in the site metadata.
  description: >
    BookSmart Financials is a full-service bookkeeping firm that provides bookkeeping, payroll, and tax services to
    small businesses and individuals.
  
  # Links to the company’s social media profiles
  socials:
    - name: Facebook
      icon: fa-facebook-official
      url: https://www.facebook.com/
    - name: Google
      icon: fa-google
      url: https://www.google.com/search?q=BookSmart+Financials
