main:
  - name: Home
    url: '#home'
    weight: 1
  - name: Services
    url: '#services'
    weight: 2
  - name: Gallery
    url: '#gallery'
    weight: 3
  - name: Reviews
    url: '#reviews'
    weight: 4
  - name: Contact
    url: '#contact'
    weight: 5

sitemap:
  - name: Home
    url: '#'
    weight: 1
  - name: Contact
    url: 'contact'
    weight: 2