main:
  - name: Home
    url: '#home'
    weight: 1
  - name: About
    url: '#about'
    weight: 2
  - name: Service
    url: '#service'
    weight: 3
  - name: Resume
    url: '#resume'
    weight: 4
  - name: Contact
    url: '#contact'
    weight: 5

sitemap:
  - name: About me
    url: about
    weight: 1
  - name: Frequently Ask Question
    url: '#'
    weight: 2
  - name: Privacy & Policy
    url: '#'
    weight: 3
  - name: Latest Article
    url: '#'
    weight: 4