author: Adriano Ferreira
logo: images/logo.png
socials:
  - name: Facebook
    icon: fa-facebook-official
    url: https://www.facebook.com/p/Firm-Contracting-100035335701052/
  - name: Google
    icon: fa-google
    url: https://www.google.com/search?q=firm+contracting